{% set name = "pycudadecon" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e9d67bab6253cd7c2d416fe9e4aba2e2a818b728bb0ba29f4759d1f0dcfc3cef

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=3.8
    - numpy
    - cudadecon >=0.7.0
    - tifffile >=0.14.0
    - typing_extensions

test:
  imports:
    - pycudadecon
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/tlambert03/pycudadecon
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python wrapper for cudaDecon - GPU accelerated 3D deconvolution for microscopy
  description: |
    This package provides a python wrapper and convenience functions for cudadecon,
    a CUDA/C++ implementation of an accelerated Richardson Lucy Deconvolution algorithm.
    It is suitable for general deconvolution of 3D microscopy data, but also has functionality
    for stage-scanning light sheet applications such as Lattice Light Sheet.
  doc_url: https://pycudadecon.readthedocs.io/
  dev_url: https://github.com/tlambert03/pycudadecon

extra:
  recipe-maintainers:
    - tlambert03
    - zbarry
